const mods = [
  { slug: "advancement-plaques-fabric" },
  { slug: "advancementinfo" },
  { slug: "badpackets" },
  { slug: "chatheads" },
  { slug: "cit-resewn" },
  { slug: "cloth-config" },
  { slug: "durability-notifier" },
  { slug: "fabric-api" },
  { slug: "forge-config-api-port-fabric" },
  { slug: "free-cam" },
  { slug: "gamma-utils" },
  { slug: "horsestatsvanilla" },
  { slug: "iceberg-fabric" },
  { slug: "indium" },
  { slug: "inventory-hud-forge" },
  { slug: "litematica" },
  { slug: "logical-zoom" },
  { slug: "malilib" },
  { slug: "minihud" },
  { slug: "modmenu" },
  { slug: "nofog" },
  { slug: "shulkerboxtooltip" },
  { slug: "sodium" },
  { slug: "visuality" },
  { slug: "wthit" },
];

module.exports = mods;
